### ISSUE TITLE
eigen313 library

### ISSUE THREAD

**Issue by mahdimohammadi** [mcprakash/ardunav#1]
Hi
I searched and attached all of the libraries of your project but i cant find the "eigen313.h"
i tried these but doesn't work :
https://github.com/vancegroup/EigenArduino
http://eigen.tuxfamily.org
can you help me by share "eigen313.h" library ?
thanks a lot.

**Comment by mcprakash** [comment]
Hi Mahdi
 I am attaching the link where you can download the Eigen313,zip. Please follow the instruction to put the folder in the correct directory. 

Link to page containing Eigen313.h - http://forum.arduino.cc/index.php?topic=144446.0

If you like my project, please like it on github and youtube. 

Thanks
Chandra
